# CMake generated Testfile for 
# Source directory: /home/edirent/Polytope/engine/paper
# Build directory: /home/edirent/Polytope/build-release-native/engine/paper
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[PaperModule_DefaultsToNoNetwork]=] "/home/edirent/Polytope/build-release-native/engine/paper/paper_skeleton_tests" "PaperModule_DefaultsToNoNetwork")
set_tests_properties([=[PaperModule_DefaultsToNoNetwork]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;83;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[PaperModule_PublicContractsCompile]=] "/home/edirent/Polytope/build-release-native/engine/paper/paper_skeleton_tests" "PaperModule_PublicContractsCompile")
set_tests_properties([=[PaperModule_PublicContractsCompile]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;83;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[PaperTools_TargetAvailable]=] "/home/edirent/Polytope/build-release-native/engine/paper/paper_skeleton_tests" "PaperTools_TargetAvailable")
set_tests_properties([=[PaperTools_TargetAvailable]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;83;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[PaperEvent_IsObservationOnly]=] "/home/edirent/Polytope/build-release-native/engine/paper/paper_skeleton_tests" "PaperEvent_IsObservationOnly")
set_tests_properties([=[PaperEvent_IsObservationOnly]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;83;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[PaperSnapshot_DefaultsSafe]=] "/home/edirent/Polytope/build-release-native/engine/paper/paper_skeleton_tests" "PaperSnapshot_DefaultsSafe")
set_tests_properties([=[PaperSnapshot_DefaultsSafe]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;83;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[PaperTradingEngine_ExecutionReportUpdatesDashboard]=] "/home/edirent/Polytope/build-release-native/engine/paper/paper_trading_engine_tests" "PaperTradingEngine_ExecutionReportUpdatesDashboard")
set_tests_properties([=[PaperTradingEngine_ExecutionReportUpdatesDashboard]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;102;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[PaperTradingEngine_OpportunityDoesNotCreatePnL]=] "/home/edirent/Polytope/build-release-native/engine/paper/paper_trading_engine_tests" "PaperTradingEngine_OpportunityDoesNotCreatePnL")
set_tests_properties([=[PaperTradingEngine_OpportunityDoesNotCreatePnL]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;102;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[PaperTradingEngine_RiskDecisionDoesNotChangeLedger]=] "/home/edirent/Polytope/build-release-native/engine/paper/paper_trading_engine_tests" "PaperTradingEngine_RiskDecisionDoesNotChangeLedger")
set_tests_properties([=[PaperTradingEngine_RiskDecisionDoesNotChangeLedger]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;102;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[PaperTradingWorkflow_ExposesLatestDashboard]=] "/home/edirent/Polytope/build-release-native/engine/paper/paper_trading_engine_tests" "PaperTradingWorkflow_ExposesLatestDashboard")
set_tests_properties([=[PaperTradingWorkflow_ExposesLatestDashboard]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;102;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[VerifyPaperTradingWorkflow_PositiveFixtureRuns]=] "/home/edirent/Polytope/build-release-native/engine/paper/verify_paper_trading_workflow_tests" "VerifyPaperTradingWorkflow_PositiveFixtureRuns")
set_tests_properties([=[VerifyPaperTradingWorkflow_PositiveFixtureRuns]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;126;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[VerifyPaperTradingWorkflow_DeterministicHashes]=] "/home/edirent/Polytope/build-release-native/engine/paper/verify_paper_trading_workflow_tests" "VerifyPaperTradingWorkflow_DeterministicHashes")
set_tests_properties([=[VerifyPaperTradingWorkflow_DeterministicHashes]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;126;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[VerifyPaperTradingWorkflow_EmitsSummary]=] "/home/edirent/Polytope/build-release-native/engine/paper/verify_paper_trading_workflow_tests" "VerifyPaperTradingWorkflow_EmitsSummary")
set_tests_properties([=[VerifyPaperTradingWorkflow_EmitsSummary]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;126;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[PaperLedger_InitialCash]=] "/home/edirent/Polytope/build-release-native/engine/paper/paper_ledger_tests" "PaperLedger_InitialCash")
set_tests_properties([=[PaperLedger_InitialCash]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;150;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[PaperLedger_ApplyBuyFill]=] "/home/edirent/Polytope/build-release-native/engine/paper/paper_ledger_tests" "PaperLedger_ApplyBuyFill")
set_tests_properties([=[PaperLedger_ApplyBuyFill]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;150;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[PaperLedger_RejectsDuplicateExecutionReport]=] "/home/edirent/Polytope/build-release-native/engine/paper/paper_ledger_tests" "PaperLedger_RejectsDuplicateExecutionReport")
set_tests_properties([=[PaperLedger_RejectsDuplicateExecutionReport]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;150;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[PaperLedger_TracksFees]=] "/home/edirent/Polytope/build-release-native/engine/paper/paper_ledger_tests" "PaperLedger_TracksFees")
set_tests_properties([=[PaperLedger_TracksFees]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;150;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[PaperLedger_UpdatesCash]=] "/home/edirent/Polytope/build-release-native/engine/paper/paper_ledger_tests" "PaperLedger_UpdatesCash")
set_tests_properties([=[PaperLedger_UpdatesCash]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;150;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[PaperLedger_OpportunityAndRiskEventsDoNotProducePnL]=] "/home/edirent/Polytope/build-release-native/engine/paper/paper_ledger_tests" "PaperLedger_OpportunityAndRiskEventsDoNotProducePnL")
set_tests_properties([=[PaperLedger_OpportunityAndRiskEventsDoNotProducePnL]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;150;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[Adapter_ExecutionReportCreatesFillEvent]=] "/home/edirent/Polytope/build-release-native/engine/paper/paper_event_adapter_tests" "Adapter_ExecutionReportCreatesFillEvent")
set_tests_properties([=[Adapter_ExecutionReportCreatesFillEvent]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;168;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[Adapter_OpportunityIntentDoesNotCreateFill]=] "/home/edirent/Polytope/build-release-native/engine/paper/paper_event_adapter_tests" "Adapter_OpportunityIntentDoesNotCreateFill")
set_tests_properties([=[Adapter_OpportunityIntentDoesNotCreateFill]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;168;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[Adapter_RiskDecisionDoesNotChangeLedger]=] "/home/edirent/Polytope/build-release-native/engine/paper/paper_event_adapter_tests" "Adapter_RiskDecisionDoesNotChangeLedger")
set_tests_properties([=[Adapter_RiskDecisionDoesNotChangeLedger]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;168;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[PositionLedger_BuyIncreasesQty]=] "/home/edirent/Polytope/build-release-native/engine/paper/position_ledger_tests" "PositionLedger_BuyIncreasesQty")
set_tests_properties([=[PositionLedger_BuyIncreasesQty]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;187;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[PositionLedger_BuyUpdatesAvgCost]=] "/home/edirent/Polytope/build-release-native/engine/paper/position_ledger_tests" "PositionLedger_BuyUpdatesAvgCost")
set_tests_properties([=[PositionLedger_BuyUpdatesAvgCost]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;187;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[PositionLedger_RejectsUnsupportedSellInV0]=] "/home/edirent/Polytope/build-release-native/engine/paper/position_ledger_tests" "PositionLedger_RejectsUnsupportedSellInV0")
set_tests_properties([=[PositionLedger_RejectsUnsupportedSellInV0]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;187;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[PaperPortfolio_BuyFillUpdatesExposure]=] "/home/edirent/Polytope/build-release-native/engine/paper/position_ledger_tests" "PaperPortfolio_BuyFillUpdatesExposure")
set_tests_properties([=[PaperPortfolio_BuyFillUpdatesExposure]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;187;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[PnL_MarksLongAtMid]=] "/home/edirent/Polytope/build-release-native/engine/paper/paper_pnl_tests" "PnL_MarksLongAtMid")
set_tests_properties([=[PnL_MarksLongAtMid]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;206;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[PnL_MarksLongAtLiquidationBid]=] "/home/edirent/Polytope/build-release-native/engine/paper/paper_pnl_tests" "PnL_MarksLongAtLiquidationBid")
set_tests_properties([=[PnL_MarksLongAtLiquidationBid]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;206;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[PnL_MissingBidIsDegraded]=] "/home/edirent/Polytope/build-release-native/engine/paper/paper_pnl_tests" "PnL_MissingBidIsDegraded")
set_tests_properties([=[PnL_MissingBidIsDegraded]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;206;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[PnL_ComputesEquityCurve]=] "/home/edirent/Polytope/build-release-native/engine/paper/paper_pnl_tests" "PnL_ComputesEquityCurve")
set_tests_properties([=[PnL_ComputesEquityCurve]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;206;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[Sharpe_InsufficientSamples]=] "/home/edirent/Polytope/build-release-native/engine/paper/performance_metrics_tests" "Sharpe_InsufficientSamples")
set_tests_properties([=[Sharpe_InsufficientSamples]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;225;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[Sharpe_ZeroVolReturnsInsufficient]=] "/home/edirent/Polytope/build-release-native/engine/paper/performance_metrics_tests" "Sharpe_ZeroVolReturnsInsufficient")
set_tests_properties([=[Sharpe_ZeroVolReturnsInsufficient]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;225;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[Drawdown_ComputesMaxDrawdown]=] "/home/edirent/Polytope/build-release-native/engine/paper/performance_metrics_tests" "Drawdown_ComputesMaxDrawdown")
set_tests_properties([=[Drawdown_ComputesMaxDrawdown]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;225;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[Performance_ComputesFillRate]=] "/home/edirent/Polytope/build-release-native/engine/paper/performance_metrics_tests" "Performance_ComputesFillRate")
set_tests_properties([=[Performance_ComputesFillRate]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;225;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[Regime_HealthyWhenAllOk]=] "/home/edirent/Polytope/build-release-native/engine/paper/regime_engine_tests" "Regime_HealthyWhenAllOk")
set_tests_properties([=[Regime_HealthyWhenAllOk]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;244;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[Regime_StaleWhenBookStale]=] "/home/edirent/Polytope/build-release-native/engine/paper/regime_engine_tests" "Regime_StaleWhenBookStale")
set_tests_properties([=[Regime_StaleWhenBookStale]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;244;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[Regime_RiskRejecting]=] "/home/edirent/Polytope/build-release-native/engine/paper/regime_engine_tests" "Regime_RiskRejecting")
set_tests_properties([=[Regime_RiskRejecting]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;244;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[Regime_HedgeRequired]=] "/home/edirent/Polytope/build-release-native/engine/paper/regime_engine_tests" "Regime_HedgeRequired")
set_tests_properties([=[Regime_HedgeRequired]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;244;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[DashboardReadStore_PublishesLatest]=] "/home/edirent/Polytope/build-release-native/engine/paper/dashboard_read_store_tests" "DashboardReadStore_PublishesLatest")
set_tests_properties([=[DashboardReadStore_PublishesLatest]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;262;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[DashboardReadStore_ReadsSinceSeq]=] "/home/edirent/Polytope/build-release-native/engine/paper/dashboard_read_store_tests" "DashboardReadStore_ReadsSinceSeq")
set_tests_properties([=[DashboardReadStore_ReadsSinceSeq]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;262;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
add_test([=[DashboardReadStore_DropsOldFramesWhenRingFull]=] "/home/edirent/Polytope/build-release-native/engine/paper/dashboard_read_store_tests" "DashboardReadStore_DropsOldFramesWhenRingFull")
set_tests_properties([=[DashboardReadStore_DropsOldFramesWhenRingFull]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/edirent/Polytope/engine/paper/CMakeLists.txt;262;add_test;/home/edirent/Polytope/engine/paper/CMakeLists.txt;0;")
